### PR TITLE
add workaround for ReadTheDocs search bug; also, remove photonic-crys…

### PR DESCRIPTION
**Pull request by HomerReid**
…tal image from top page of doc tree

### CODE REVIEW

**Comment by stevengj** [comment]
This needs a fix similar to the Meep fix (stevengj/meep#85), I guess.

**Comment by HomerReid** [comment]
I implemented said fix in the most recent commit to the FixDocSearch branch of my libctl fork.

**Comment by stevengj** [comment]
Thanks.  Is this also filed upstream somewhere?  i.e. as a mkdocs issue or something?

**Comment by HomerReid** [comment]
Yes, there's an extensive discussion dating back 2+ years on the readthedocs github page, see e.g

https://github.com/rtfd/readthedocs.org/issues/1487

It seems the issue is not a priority for the readthedocs developers because it only affects mkdocs-based documentation trees, which they consider ancillary to their primary mission of supporting RST-based trees.

**Pull request merged**
